name: Gradle Build (No Tests)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build without tests
      run: ./gradlew build -x test

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: built-jar
        path: build/libs/*.jar
